### ISSUE TITLE
item listener is called twice.

### ISSUE THREAD

**Issue by oilyu** [StanKocken/EfficientAdapter#24]
Hi, Thanks for your library.
But when i clicked the recycleview's item, i found the item listener was called twice. So I read the library code, i found you set TWO times call back in the ViewHolderClickListener .

**Comment by StanKocken** [comment]
Good catch. Sorry about that.
I pushed to fix to this repository and I will upload to JCenter the version 2.1.1 within the next 24h.
Thanks.

**Comment by OilLyu** [comment]
May be you forgot to upload the library to JCenter the version 2.1.1.
